---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/9/2022 1:57 AM
---
local Event = require('__stdlib__/stdlib/event/event')

local refresh_data = function()
    print('RUn 22222')
    remote.call('enemy_race_manager', 'force_data_reindex')
    remote.call('enemy_race_manager', 'army_reindex')
end

Event.on_init(function(event)
    refresh_data()
end)

Event.on_configuration_changed(function(event)
    refresh_data()
end)